apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: notification
  name: notification
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: notification-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: notification
  labels:
    microservice: notifications-service # Label used to map to the respective microservice in Port
    service: notification-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - image: public.ecr.aws/y8q1v8m0/fastapi-sample:latest
          imagePullPolicy: Always
          name: notification-service
          ports:
            - containerPort: 80
---

